### PR TITLE
doc: fix typos in plugin API reference

### PR DESCRIPTION
**Pull request by l**
This pull request includes two commits,
8447391200011095da43cd8b8fc09fc33d3c04b3 for regular Japanese translation update, and
851ea0082a2b8aacc4372622b3b66c7ed0d9c18f for fixing document.

Could you review 851ea0082a2b8aacc4372622b3b66c7ed0d9c18f before merge?

### CODE REVIEW

**Comment by flashcode** [comment]
Hi,
I'm currently doing lot of changes in API reference due to recent changes in API, you could maybe rebase your changes over current HEAD (things have changed, I think it will impact your commits).

**Comment by flashcode** [comment]
I'll check your commit and manually merge into API doc.

**Comment by flashcode** [comment]
I made all changes in the plugin API reference, you can now either rebase your commit into a single one on top of new HEAD, or maybe better open another pull request to update translations.
Thanks!

**Comment by l** [comment]
Thanks for manual merge. It looks that everything merged as expected.
I am closing this pull request and will open another pull request for update translations.

**Comment by l** [comment]
Thanks for manual merge. It looks that everything merged as expected.
I am closing this pull request and will open another pull request for update translations.

**Pull request closed without merging**
