### PR TITLE
complete spanish quick star guide doc

### PR DESCRIPTION
**Pull request by victorhck**

### CODE REVIEW

**Comment by victorhck** [comment]
If I want to traslate FAQ doc, should also make modifications in Make and Cmake files?
Since I'm not developer, some technichal stuff are out of my skills...

**Comment by flashcode** [comment]
@victorhck: to translate FAQ to Spanish, you can copy the file `doc/en/weechat_faq.en.adoc` to `doc/es/weechat_faq.es.adoc`.
It's better if you can add it in the file `doc/es/CMakeLists.txt` so that you can compile it and check that the HTML result is OK.
But submitting only the FAQ is OK as well, I would then update all build files.

**Comment by flashcode** [comment]
@victorhck: I forgot to mention, please open a separate PR for the FAQ as it's a brand new translation in Spanish and please keep this one for quickstart only.
Thank you for your help on translations!

**Comment by victorhck** [comment]
> please open a separate PR for the FAQ as it's a brand new translation in Spanish and please keep this one for quickstart only.

How can be done that? If I'm not wrong, If I open a PR, all the commits done after that are included in that commit, right?

**Comment by flashcode** [comment]
@victorhck: you must make a separate branch with the FAQ commits only and open a PR for this branch.
And for the current PR, you have to remove FAQ commits and update the PR.

**Comment by victorhck** [comment]
well I revert the repo to e4d1916 commit, and removed the faq file, so I didn't messed up, I think that everything should be ok...

**Comment by flashcode** [comment]
Thanks, merged.

**Pull request closed without merging**
