### PR TITLE
doc: update Japanese translations

### PR DESCRIPTION
**Pull request by l**

### CODE REVIEW

**Comment by flashcode** [comment]
Thanks!

**Comment by l** [comment]
Dear flashcode,

Thanks for the merge,

At Fri, 06 May 2016 13:02:51 -0700,
Sébastien Helleu wrote:
> 
> Merged #728.

It would be nice for me,
If you keep author name and address
which is used in the pull-requested commit.

Sincerely yours,
Ryuunosuke Ayanokouzi
-- 
AYANOKOUZI, Ryuunosuke <i38w7i3@yahoo.co.jp>

**Comment by flashcode** [comment]
I kept everything in the pull request, I just pressed the "Merge" button.
So it should keep your name and email address used in your commit.

**Comment by flashcode** [comment]
In your commit, github shows a tooltip saying "Unrecognized author". So for me the issue is in the commit, not the merge.

**Comment by flashcode** [comment]
It looks like the email used in commit is not associated with your GitHub account maybe?

**Comment by l** [comment]
Dear flashcode,

At Fri, 06 May 2016 23:52:47 -0700,
Sébastien Helleu wrote:
> 
> I kept everything in the pull request, I just pressed the "Merge" button.
> So it should keep your name and email address used in your commit.

Have you done the same as before?
If yes, merge behavior by GitHub might be changed recently.

In the previous pull requests,
you have created a merge commit for each pull request.
For instance, for my pull request #720, merge commit
5c8f540c47f98bad429e39eab326e2681ec6a083 is created.
This behavior is similar to the behavior of merge --no-ff.

But for this pull request #728,
merge commit is not created and single commit 
2d5ea374af310924aea225ecd42d5eb0fd2d2e96 with the same change
as pull-requested commit 97114c2f63591237cb4a60ed79303fd927f7814a
(with different author/comitter/date) is created.
This behavior is similar to the behavior of merge --ff.

$ git diff 2d5ea374af310924aea225ecd42d5eb0fd2d2e96 97114c2f63591237cb4a60ed79303fd927f7814a
$ git log --show-signature --color --stat --pretty=fuller -1 2d5ea374af310924aea225ecd42d5eb0fd2d2e96
commit 2d5ea374af310924aea225ecd42d5eb0fd2d2e96
Author:     l <l@users.noreply.github.com>
AuthorDate: Sat May 7 05:02:50 2016 +0900
Commit:     Sébastien Helleu <flashcode@flashtux.org>
CommitDate: Fri May 6 22:02:50 2016 +0200

    doc: update Japanese translations (#728)

 doc/ja/weechat_faq.ja.asciidoc | 21 ++++++++-------------
 1 file changed, 8 insertions(+), 13 deletions(-)
$ git log --show-signature --color --stat --pretty=fuller -1 97114c2f63591237cb4a60ed79303fd927f7814a
commit 97114c2f63591237cb4a60ed79303fd927f7814a
Author:     AYANOKOUZI, Ryuunosuke <i38w7i3@yahoo.co.jp>
AuthorDate: Fri May 6 09:00:00 2016 +0900
Commit:     AYANOKOUZI, Ryuunosuke <i38w7i3@yahoo.co.jp>
CommitDate: Fri May 6 09:00:00 2016 +0900

    doc: update Japanese translations

 doc/ja/weechat_faq.ja.asciidoc | 21 ++++++++-------------
 1 file changed, 8 insertions(+), 13 deletions(-)

At Fri, 06 May 2016 23:53:50 -0700,
Sébastien Helleu wrote:
> 
> In your commit, github shows a tooltip saying "Unrecognized author". So for me the issue is in the commit, not the merge.

At Sat, 07 May 2016 00:14:27 -0700,
Sébastien Helleu wrote:
> 
> It looks like the email used in commit is not associated with your GitHub account maybe?

Name and Email used in pull-requested commit 97114c2f63591237cb4a60ed79303fd927f7814a
are "AYANOKOUZI, Ryuunosuke" and "i38w7i3@yahoo.co.jp" as usual.
These information is not associated with any GitHub account.

Sincerely yours,
Ryuunosuke Ayanokouzi
-- 
AYANOKOUZI, Ryuunosuke <i38w7i3@yahoo.co.jp>

**Comment by flashcode** [comment]
I think this is not relative to the type of merge. Now GitHub can do merge without merge commit, but that's not the problem.
If I look at your pull request commit, I can see your name with "Unrecognized author", and I can not click on your name or icon to view your profile. So it seems your email is not associated to your GitHub account.
Maybe now this is required by GitHub?

Note: when I look at other pull requests, I have not same problem (the author is recognized and I can click on name/icon).

**Comment by flashcode** [comment]
I'll try to merge your commit on weechat.org with `--no-ff`, and check the result.

**Comment by flashcode** [comment]
With `--no-ff` this seems OK (but I think you should associate your email anyway in your account, to prevent such problem).

**Comment by Mikaela** [comment]
@l I think you have enabled checked "Keep my email address private" which is possibly causing the trouble. Maybe you should check it with instructions from https://help.github.com/articles/keeping-your-email-address-private/ ?

**Comment by l** [comment]
Dear flashcode,

Thanks for reply.

At Sat, 07 May 2016 06:27:31 -0700,
Sébastien Helleu wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> [2  <text/html; UTF-8 (7bit)>]
> I think this is not relative to the type of merge. Now GitHub can do merge
> without merge commit, but that's not the problem.
> If I look at your pull request commit, I can see your name with
> "Unrecognized author", and I can not click on your name or icon to view your
> profile. So it seems your email is not associated to your GitHub account.
> Maybe now this is required by GitHub?
> 
> Note: when I look at other pull requests, I have not same problem (the
> author is recognized and I can click on name/icon).

OK, I understand that my email is not associated with l GitHub account.
This is true. But this is not a main problem for me.

Essence of the problem is that 
GitHub's "Squash and merge" overwrite author's information
from true author to pull-request sender.
Moreover, as far as we use Git from command line,
this type of problem (author's information of commit is overwritten
from true author to pull-request sender) never happened.

If pull-request sender is sharing his identity with true author
(this is true in a large number of cases), overwritten of
author's information to pull-request sender does not cause problem.
But, if pull-request sender is just an agent of true author
(this is my case), such overwritten cause problem.

Suppose there is a bug/mistake in the commit (merged by "Squash and merge") [1],
bug submitter who don't have GitHub account will
find author's address "l@users.noreply.github.com" by "git blame"
and send issues by e-mail to the address,
But the domain "users.noreply.github.com" has no MX record,
the mail will be returned to the bug submitter.

This means, GitHub's "Squash and merge" disturbs the collaboration with
outsider (who does not have GitHub account) for project running on GitHub.

In my opinion, using GitHub's "Squash and merge" is still controversial.

what do you think about this?

[1] https://github.com/weechat/weechat/commit/2d5ea374af310924aea225ecd42d5eb0fd2d2e96

At Sat, 07 May 2016 06:28:16 -0700,
Sébastien Helleu wrote:
> 
> I'll try to merge your commit on weechat.org with --no-ff, and check the
> result.

At Sat, 07 May 2016 06:30:30 -0700,
Sébastien Helleu wrote:
> 
> With --no-ff this seems OK (but I think you should associate your email
> anyway in your account, to prevent such problem).

It looks that my pull request
to weechat.org repository is merged by "Create a merge commit" [2]
and to weechat repository is merged by "Squash and merge" [3].
I prefer "Create a merge commit", because it will keep author information.
"Squash and merge" by others is bad for me.
Because, before I open a pull request,
I always squash all my private commits into single commit by myself
and rebase my working copy to latest "master" branch.

If you are worried that merge commit
by "Create a merge commit" makes git history complicated,
how about trying Fast-forward merge (merge --ff) or
rebasing branch (both will keep git history straightforward and
author information also).

[2] https://github.com/weechat/weechat.org/pull/52
[3] https://github.com/weechat/weechat/pull/728

I am looking forward to your reply.

Sincerely yours,
Ryuunosuke Ayanokouzi
-- 
AYANOKOUZI, Ryuunosuke <i38w7i3@yahoo.co.jp>

**Comment by l** [comment]
Dear Mikaela,

Thanks for suggestion,

At Sat, 07 May 2016 06:34:02 -0700,
Mikaela Suomalainen wrote:
>
> @l I think you have enabled checked "Keep my email address private" which is
> possibly causing the trouble. Maybe you should check it with instructions
> from https://help.github.com/articles/keeping-your-email-address-private/ ?

I have turned the feature ON since long before.
But this feature is not concerned with the issue, I think.

The essence of this problem is that GitHub's
"Squash and merge" method, which is recently launched[1],
easily change author's information of commits:
true author's identification is overwritten by
pull-request sender's identification.

If pull-request sender does not share his identification with true author,
the author information of the commit generated by "Squash and merge" method
means nothing. To make matters worse, pull-request sender
will take the blame for all the modification by squashed commits.

"Squash and merge" method is only justified, when single person
(identification) did whole work concerned with the pull request.
In most case, traditional GitHub's "Create a merge commit" method or
"Fast forward merge" or "rebasing branch" by command-line is preferred.
Because these three method will keep author's information.

In my opinion, Keeping author's identification is important to
clarify the person on whom the responsibility lies.
For each commit, the one who is responsible for the modification is
the true author, not pull-request sender.

Sincerely yours,
Ryuunosuke Ayanokouzi
--
AYANOKOUZI, Ryuunosuke <i38w7i3@yahoo.co.jp>

**Comment by Mikaela** [comment]
Ah, now I understand the problem, I had missed that entirely.

It's [this new feature launched on April 1st](https://github.com/blog/2141-squash-your-commits), which also has [GitHub help page here](https://help.github.com/articles/about-pull-request-merge-squashing/) and [instructions on how to retain the old behaviour here](https://help.github.com/articles/configuring-pull-request-merge-squashing/) which @flashcode should possibly visit.

It appears to do squashing with `--author` flag and also erasing GPG signature if any existed. I have noticed that with other project and wondered why it was like that.

**Comment by flashcode** [comment]
I disabled the squash merging of commits in this repository, so this should solve the problem.

**Comment by l** [comment]
Dear flashcode,

Thanks for reply.

At Sun, 08 May 2016 11:42:29 -0700,
Sébastien Helleu wrote:
> 
> I disabled the squash merging of commits in this repository, so this should solve the problem.

Thanks for your understanding.
Last but not the least, "git merge --ff" always be with us.
We can avoide merge commit by this command.

Sincerely yours,
Ryuunosuke Ayanokouzi
-- 
AYANOKOUZI, Ryuunosuke <i38w7i3@yahoo.co.jp>

**Pull request merged**
