### PR TITLE
doc/api: Add values for hook_process constants

### PR DESCRIPTION
**Pull request by trygveaa**
When logging this value I just see a number so I have to look up what it means. Previously you would have to check the code or print the value of each of these constants to see it. Seeing the value directly in the documentation makes this much easier.

### CODE REVIEW

**Comment by flashcode** [comment]
Hi,

This constant is used only in C API, not scripting API, see the note where it's defined: https://github.com/weechat/weechat/blob/master/src/plugins/weechat-plugin.h#L157

So if you agree, I'll just close this PR.

**Comment by trygveaa** [comment]
Ah, okay

**Comment by trygveaa** [comment]
@flashcode: Wait, didn't you mean to comment this in PR #1823? This PR is still relevant.

**Comment by flashcode** [comment]
Sorry, I closed the wrong one.

**Pull request merged**
