### PR TITLE
Avoiding conditional directives that break statements

### PR DESCRIPTION
**Pull request by RomeroMalaquias**
Hello,
this change is only aesthetical, it's a suggestion to avoid the use of conditional directives that break statements. I think this will improve your coding rules.

### CODE REVIEW

**Comment by RomeroMalaquias** [comment]
Hello,
what kind of information is expected?

**Comment by flashcode** [comment]
Hi @RomeroMalaquias,

I wrote one comment with two remarks on the commit, did you see it?

**Comment by RomeroMalaquias** [comment]
@flashcode , sorry, i can't find the remarks, or github isn't showing to me.
0 comments on commit b5301a9

**Comment by flashcode** [comment]
@RomeroMalaquias: I said:

I think for clarity you should move this line inside the following `if (num_read < 0)`, otherwise there's no check of errors.
And I would use parentheses around condition, so that we see immediately this is a boolean result: `verify_err = (errno == EAGAIN);`

**Comment by RomeroMalaquias** [comment]
Ok @flashcode , fixing now

**Comment by flashcode** [comment]
Thanks, I'll merge after the release (scheduled tomorrow).

**Comment by RomeroMalaquias** [comment]
Thanks for your time

**Comment by flashcode** [comment]
Merged (with minor changes).
Thanks.

**Pull request closed without merging**
