### PR TITLE
Added a first fuzzer for several string operations.

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Hi guys,

Cross referencing https://github.com/weechat/weechat/issues/1462 
I have implemented an initial fuzzer and integrated with OSS-fuzz. I have more in the pipeline but figured it would be nice to start small.

David

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
Any news on this @flashcode ?

**Comment by txtsd** [comment]
I'm eager to see this fuzzer added and improved on!

**Comment by DavidKorczynski** [comment]
@AdamKorcz and I would be very happy to work on integrating fuzzing into weechat - I started it here as it would be nice to get the process going first before we commit more time to it. I also opened a PR on the OSS-Fuzz side of thing (https://github.com/google/oss-fuzz/pull/3584) but I closed it just a few hours ago since I wasn't sure if you were interested here - I can naturally reopen once we progress.

**Comment by flashcode** [comment]
Hi @DavidKorczynski,

Thanks for the PR.

I recently added in WeeChat a way to create fake IRC servers, for now they are used in tests to simulate messages received from the server, see: https://github.com/weechat/weechat/blob/f3b9eb979da01293e44760ba6d68cce937fdd313/tests/unit/plugins/irc/test-irc-protocol.cpp#L293-L306

And my goal is to use that in a fuzzer. Simulating incoming IRC messages will cover:

- IRC protocol functions (interesting, CVE were found recenlty here)
- many string functions, including the ones you are testing here.

So I think it's a better approach to cover more code via the fuzzer.

**Pull request closed without merging**
