### PR TITLE
irc: add support for IRCv3.2 Client Capability Negotiation (closes #586)

### LINKED ISSUE #586: IRCv3.2 Client Capability Negotiation (CAP 3.2)
- http://ircv3.net/specs/core/capability-negotiation-3.2.html

Without having any coding skills etc. it seems simple to implement and would also work towards https://github.com/weechat/weechat/issues/413 by making IRCv3.2 servers send the list of SASL mechanisms they support.

### PR DESCRIPTION
**Pull request by sim642**
In addition to implementing required changes to support capabilities with values and `CAP LS`/`CAP LIST` split across multiple lines, this patch also adds client-side tracking of all capabilities. This means that weechat/plugins/scripts/triggers can easily check if some capability is available or enabled, instead of having to somehow check itself.

This also modifies `/cap` command to uppercase the subcommand which it can autocomplete because servers may require it to be uppercase.

API was changed to allow keeping track of server capabilities across upgrading so the hashtable needs to be restored from an infolist.

There's a few places with comments like `WeeChat x.y.z` which need to be updated to the proper WeeChat version this gets merged into.

_NB! This patch is in conflict with #580. I would merge this before as it's a more core change. I could modify #580 to easily merge on top of this once this gets merged._

### CODE REVIEW

**Comment by KamranMackey** [comment]
@sim642 is there anyway you could merge all your PRs into one branch, that way I can use the patches? I keep getting errors when trying to apply the PRs to my local repo manually.

**Comment by flashcode** [comment]
@KamranMackey: the pull requests will be merged one by one.
You just need some patience, I don't have time at all for now to check and merge them :-(

**Comment by sim642** [comment]
@KamranMackey: I took a shot at creating a separate branch in my fork which has all my open PRs merged into it: https://github.com/sim642/weechat/tree/merge. I can't guarantee everything still works though because I might have made some errors trying to quickly solve all the merge conflicts.

**Comment by KamranMackey** [comment]
@sim642 thank you! :)

**Comment by Mikaela** [comment]
And now there is merge conflict :(

**Comment by sim642** [comment]
@Mikaela, The conflict is due to #351 having been merged as that added some code which uses `server->cap_account_notify`, a variable this PR replaces with a generic hashtable of capabilities in use. It's an easy fix for me but I won't rebase my PR yet because there's still plenty of other PRs in the queue before this one to be merged and I'd rather not have to rebase this amount of code multiple times. I will fix this conflict once the time comes to merge this PR.

(cc: @flashcode)

**Pull request merged**
