### PR TITLE
python: add workaround for crash on unload with Python 3.12

### LINKED ISSUE #2046: weechat crashes on exit when both title.py and autosort.py are loaded (voidlinux)
## Bug summary
When using weechat-4.1.1_1 and weechat-python-4.1.1_1 under voidlinux. When scripts title.py and autosort.py are both installed weechat crashes on exit.

## Steps to reproduce

1. /script load title.py 
2. /script load autosort.py
3. /exit

If no crash at this time then reloading weechat and /exit will definitely crash weechat in voidlinux.

## Current behavior

Weechat crashes during exit when both scripts are installed.

## Expected behavior

Weechat doesn't crash on exit when both scripts are installed.

## Additional information

After bulding debug packages in voidlinux

gdb /usr/bin/weechat

Program received signal SIGSEGV, Segmentation fault.
                                                                             0x00007ffff626f76d in PyObject_GC_UnTrack () from /usr/lib/libpython3.12.so.1.0

bt full
```
#0  0x00007ffff626f76d in PyObject_GC_UnTrack () from /usr/lib/libpython3.12.so.1.0
No symbol table info available.
#1  0x00007ffff62a2099 in ?? () from /usr/lib/libpython3.12.so.1.0
No symbol table info available.
#2  0x00007ffff62251e5 in ?? () from /usr/lib/libpython3.12.so.1.0
No symbol table info available.
#3  0x00007ffff6220276 in ?? () from /usr/lib/libpython3.12.so.1.0
No symbol table info available.
#4  0x00007ffff6225bd5 in _PyModule_ClearDict () from /usr/lib/libpython3.12.so.1.0
No symbol table info available.
#5  0x00007ffff62eaaf6 in ?? () from /usr/lib/libpython3.12.so.1.0
No symbol table info available.
#6  0x00007ffff62ead6b in Py_EndInterpreter () from /usr/lib/libpython3.12.so.1.0
No symbol table info available.
#7  0x00007ffff66ea2a0 in weechat_python_unload (script=0x555555df3550)
    at /builddir/weechat-4.1.1/src/plugins/python/weechat-python.c:975
        rc = <optimized out>
        interpreter = 0x7ffff5bec910
        filename = 0x555555e69230 "/home/roald/.local/share/weechat/python/autoload/title.py"
#8  0x00007ffff66ea375 in weechat_python_unload_all ()
    at /builddir/weechat-4.1.1/src/plugins/python/weechat-python.c:1024
No locals.
#9  0x00007ffff670a12c in plugin_script_end (weechat_plugin=weechat_plugin@entry=0x555555b5cd10, 
    plugin_data=plugin_data@entry=0x7ffff671bd00 <python_data>)
    at /builddir/weechat-4.1.1/src/plugins/plugin-script.c:1789
        scripts_loaded = 1
#10 0x00007ffff66eb681 in weechat_plugin_end (plugin=0x555555b5cd10)
    at /builddir/weechat-4.1.1/src/plugins/python/weechat-python.c:1563
No locals.
#11 0x00005555555fadb6 in plugin_unload (plugin=0x555555b5cd10)
    at /builddir/weechat-4.1.1/src/plugins/plugin.c:1253
        end_func = <optimized out>
        name = 0x555555fcd320 "python"
#12 0x00005555555fae69 in plugin_unload_all () at /builddir/weechat-4.1.1/src/plugins/plugin.c:1305
        plugins_loaded = <optimized out>
#13 0x00005555555fb122 in plugin_end () at /builddir/weechat-4.1.1/src/plugins/plugin.c:1425
No locals.
#14 0x00005555555630c2 in weechat_end (gui_end_cb=0x5555555f43d0 <gui_main_end>)
    at /builddir/weechat-4.1.1/src/core/weechat.c:708
No locals.
#15 0x00005555555620d6 in main (argc=1, argv=0x7fffffffe118)
    at /builddir/weechat-4.1.1/src/gui/curses/normal/main.c:45
No locals.
```

---

- WeeChat version:  weechat-4.1.1_1
- OS, distribution and version:  Voidlinux (fully updated on Tue Nov 21 2023)
- Terminal: foot
- Terminal multiplexer (screen/tmux/…/none): none

### PR DESCRIPTION
**Pull request by trygveaa**
Python 3.12 has a bug where it crashes when you unload all the interpreters unless you make sure to unload the first interpreter you loaded last. For some reason, loading the eval interpreter before any scripts also seems to prevent the issue, even if the eval interpreter is unloaded before the other interpreters.

So this just evals an empty string at the end of initing the Python plugin if the Python version is 3.12, to make sure the eval interpreter is loaded first.

Fixes #2046

### CODE REVIEW

**Comment by adsr** [comment]
Hm, this doesn't seem to fix it on my end.

(Python 3.13 does fix.)

**Comment by trygveaa** [comment]
> Hm, this doesn't seem to fix it on my end.

Oh :/ Okay, thanks for testing. I pushed another commit now, could you test that and see if it helps?

Also, make sure that `python.look.eval_keep_context` is enabled (which is the default).

**Comment by adsr** [comment]
No problem, thank you for working on this. Same result with the extra commit. Confirmed `eval_keep_context` is on.

I was drawn to your comment at https://github.com/python/cpython/issues/116510:

> Interestingly, the segmentation fault doesn't happen if the script that was loaded last is unloaded first.

We seem to be unloading plugin LIFO order already:

https://github.com/weechat/weechat/blob/7cf45707ea10df00a73e9a8a0bd2338fcad9a0d4/src/plugins/plugin.c#L1303-L1306

Am I missing another detail?

**Comment by flashcode** [comment]
Fix works for me with Python 3.12.4, I'm merging, at least it should work for most people and it's not worst for the others…

**Comment by flashcode** [comment]
I also pushed the same fix on branch 4.3 (future version 4.3.4).

**Comment by adsr** [comment]
On my backlog to test. Apologies for delay.

**Comment by adsr** [comment]
Hi @flashcode. Apologies for the delay. I confirmed 4.3.5 works fine with Python 3.12.x. Thanks.

**Pull request merged**
