### PR TITLE
php: fix PHP 8+ build (#1599)

### PR DESCRIPTION
**Pull request by adsr**
@flashcode 's test script [here](https://github.com/weechat/weechat/issues/1599#issuecomment-743989124) works with this patch on PHP 8.1.0-dev and 7.4.18 on my setup. I fixed one bug in `weechat_php_load`.

Note the PHP build now outputs `libphp.so` by default (not `libphp8.so`). I'm not sure what packagers will decide to do with this, so I made the autoconf script check a broad variety of locations and try both `-lphp8` and `-lphp`. (I wish `php-config` outputted the library name.) ~`FindPHP.cmake` seems to handle this already.~ I forgot I edited `FindPHP.cmake` slightly too to handle this case.

TODO Test on Ubuntu 21.10.

TODO Add real function signatures to `weechat-php.stub.php` and regenerate arginfo files, otherwise PHP built with `--enable-debug` will fatal with `Arginfo / zpp mismatch` on the first `weechat_` function call. This task will be kind of tedious unless there's a code-gen tool I'm unware of.

### CODE REVIEW

**Comment by flashcode** [comment]
Hi @adsr,

Thanks for the changes, I'm testing them.

I have 2 issues, one compilation warning:

```
[ 50%] Building C object src/plugins/php/CMakeFiles/php.dir/weechat-php.c.o
/home/flashcode/src/weechat/dev/src/plugins/php/weechat-php.c: In function ‘weechat_php_load’:
/home/flashcode/src/weechat/dev/src/plugins/php/weechat-php.c:703:26: warning: assignment to ‘const char *’ from incompatible pointer type ‘zend_string *’ {aka ‘struct _zend_string *’} [-Wincompatible-pointer-types]
  703 |     file_handle.filename = zend_string_init(filename, strlen(filename), 0);
      |                          ^
```

And I'm not able to load any PHP script, with PHP 7 and 8, I have the following error in WeeChat when I do `/script load /tmp/test.php`:

```
    | php: loading script "/tmp/test.php"
    | php: PHP Warning:  Unknown: Failed to open stream: No such file or directory in Unknown on line 0
    | php: PHP Fatal error:  Failed opening required ' ' (include_path='.:/usr/share/php') in Unknown on line 0
=!= | php: function "register" not found (or failed) in file "/tmp/test.php"
```

Maybe related to the compiler warning shown above?

The PHP script, working fine with PHP 7 and the master branch (so without your changes):

```
<?php

$command_cb = function ($data, $buffer, $args) {
    weechat_print("", "php command_cb: data=" . $data . ", buffer=" . $buffer . ", args=" . $args);
    return WEECHAT_RC_OK;
};

weechat_register("test", "FlashCode", "0.1", "GPL3", "test", "", "");
weechat_print("", "Hey, I'm a PHP script!");

weechat_hook_command("testphp", "description", "args", "desc_args", "", $command_cb, "my_data");
```

**Comment by flashcode** [comment]
Note: I rebased your PR on master locally to do my tests.

**Comment by adsr** [comment]
Ah yes, I forgot an ifdef. Fixed by https://github.com/weechat/weechat/pull/1668/commits/cbcbd6e3911da60a24c7e56ade90980eb97fbed1. I must not have tested properly with PHP 7.4. Tested again with PHP 8.1 and 7.4. Does that fix your setup @flashcode?

**Comment by flashcode** [comment]
357 commits now, did you rebase by mistake on another branch, or…?

**Comment by flashcode** [comment]
And it works fine with your commit adding the ifdef, thanks.
I should be able to merge using my local branch.

**Comment by flashcode** [comment]
Merged!

Notes:

- I tested with Ubuntu 21.10 and PHP 8.0.8, it works fine.
- You mentioned a script `~/php-src/build/gen_stub.php` in a comment, where can I find this script?

**Comment by flashcode** [comment]
One problem remains though: the tests on PHP scripts are failing with error "zend_mm_heap corrupted". This is weird, this happens only when compiling with CMake and not with autotools: https://github.com/weechat/weechat/actions/runs/1109577250
By the way, I compile with CMake on my Debian and tests are running fine.
In the CI, tests are running on Ubuntu 20.04 and PHP 7.4 is installed from ppa:ondrej/php.

**Comment by flashcode** [comment]
The error while loading the PHP generated script for tests:

```
php: PHP Fatal error:  Only variables can be passed by reference in /home/runner/work/weechat/weechat/build-tmp-10811/tests/tmp_weechat_test/testapi/testapi.php on line 16
```

The generated PHP script is:

```php
<?php
//
// testapi.php -- WeeChat Php scripting API testing
//
// WeeChat script automatically generated by testapigen.py.
// DO NOT EDIT BY HAND!
//
// Date: 2021-08-08 07:27:39.327449
//


function check($result, $condition, $lineno)
{
    if ($result)
    {
        weechat_print("", "      TEST OK: " . $condition);
    }
    else
    {
        weechat_print("", "/home/shelleu/perso/src/weechat/dev/tests/scripts/python/testapi.py" . ":" . $lineno . ":1: " . "ERROR: [" . "testapi.php" . "] condition is false: " . $condition);
    }
}

function test_plugins()
{
    weechat_print("", "  > test_plugins");
    check(weechat_plugin_get_name("") == "core", "weechat.plugin_get_name('') == 'core'", "46");
    check(weechat_plugin_get_name(weechat_buffer_get_pointer(weechat_buffer_search_main(), "plugin")) == "core", "weechat.plugin_get_name(weechat.buffer_get_pointer(weechat.buffer_search_main(), 'plugin')) == 'core'", "47");
}

function test_strings()
{
    weechat_print("", "  > test_strings");
    check(weechat_charset_set("iso-8859-15") == 1, "weechat.charset_set('iso-8859-15') == 1", "52");
    check(weechat_charset_set("") == 1, "weechat.charset_set('') == 1", "53");
    check(weechat_iconv_to_internal("iso-8859-15", "abc") == "abc", "weechat.iconv_to_internal('iso-8859-15', 'abc') == 'abc'", "54");
    check(weechat_iconv_from_internal("iso-8859-15", "abcd") == "abcd", "weechat.iconv_from_internal('iso-8859-15', 'abcd') == 'abcd'", "55");
    check(weechat_gettext("abcdef") == "abcdef", "weechat.gettext('abcdef') == 'abcdef'", "56");
    check(weechat_ngettext("file", "files", 1) == "file", "weechat.ngettext('file', 'files', 1) == 'file'", "57");
    check(weechat_ngettext("file", "files", 2) == "files", "weechat.ngettext('file', 'files', 2) == 'files'", "58");
    check(weechat_strlen_screen("abcd") == 4, "weechat.strlen_screen('abcd') == 4", "59");
    check(weechat_string_match("abcdef", "abc*", 0) == 1, "weechat.string_match('abcdef', 'abc*', 0) == 1", "60");
    check(weechat_string_match("abcdef", "abc*", 1) == 1, "weechat.string_match('abcdef', 'abc*', 1) == 1", "61");
    check(weechat_string_match("ABCDEF", "abc*", 1) == 0, "weechat.string_match('ABCDEF', 'abc*', 1) == 0", "62");
    check(weechat_string_match_list("abcdef", "*,!abc*", 0) == 0, "weechat.string_match_list('abcdef', '*,!abc*', 0) == 0", "63");
    check(weechat_string_match_list("ABCDEF", "*,!abc*", 1) == 1, "weechat.string_match_list('ABCDEF', '*,!abc*', 1) == 1", "64");
    check(weechat_string_match_list("def", "*,!abc*", 0) == 1, "weechat.string_match_list('def', '*,!abc*', 0) == 1", "65");
    check(weechat_string_eval_path_home("test \${abc}", array(), array("abc" => "123"), array()) == "test 123", "weechat.string_eval_path_home('test \${abc}', {}, {'abc': '123'}, {}) == 'test 123'", "66");
    check(weechat_string_mask_to_regex("test*mask") == "test.*mask", "weechat.string_mask_to_regex('test*mask') == 'test.*mask'", "67");
    check(weechat_string_has_highlight("my test string", "test,word2") == 1, "weechat.string_has_highlight('my test string', 'test,word2') == 1", "68");
    check(weechat_string_has_highlight_regex("my test string", "test|word2") == 1, "weechat.string_has_highlight_regex('my test string', 'test|word2') == 1", "69");
    check(weechat_string_format_size(0) == "0 bytes", "weechat.string_format_size(0) == '0 bytes'", "70");
    check(weechat_string_format_size(1) == "1 byte", "weechat.string_format_size(1) == '1 byte'", "71");
    check(weechat_string_format_size(2097152) == "2.10 MB", "weechat.string_format_size(2097152) == '2.10 MB'", "72");
    check(weechat_string_format_size(420000000) == "420.00 MB", "weechat.string_format_size(420000000) == '420.00 MB'", "73");
    check(weechat_string_color_code_size("") == 0, "weechat.string_color_code_size('') == 0", "74");
    check(weechat_string_color_code_size("test") == 0, "weechat.string_color_code_size('test') == 0", "75");
    $str_color = weechat_color("yellow,red");
    check(weechat_string_color_code_size($str_color) == 7, "weechat.string_color_code_size(str_color) == 7", "77");
    check(weechat_string_remove_color("test", "?") == "test", "weechat.string_remove_color('test', '?') == 'test'", "78");
    check(weechat_string_is_command_char("/test") == 1, "weechat.string_is_command_char('/test') == 1", "79");
    check(weechat_string_is_command_char("test") == 0, "weechat.string_is_command_char('test') == 0", "80");
    check(weechat_string_input_for_buffer("test") == "test", "weechat.string_input_for_buffer('test') == 'test'", "81");
    check(weechat_string_input_for_buffer("/test") == "", "weechat.string_input_for_buffer('/test') == ''", "82");
    check(weechat_string_input_for_buffer("//test") == "/test", "weechat.string_input_for_buffer('//test') == '/test'", "83");
    check(weechat_string_eval_expression("100 > 50", array(), array(), array("type" => "condition")) == "1", "weechat.string_eval_expression('100 > 50', {}, {}, {'type': 'condition'}) == '1'", "84");
    check(weechat_string_eval_expression("-50 < 100", array(), array(), array("type" => "condition")) == "1", "weechat.string_eval_expression('-50 < 100', {}, {}, {'type': 'condition'}) == '1'", "85");
    check(weechat_string_eval_expression("18.2 > 5", array(), array(), array("type" => "condition")) == "1", "weechat.string_eval_expression('18.2 > 5', {}, {}, {'type': 'condition'}) == '1'", "86");
    check(weechat_string_eval_expression("0xA3 > 2", array(), array(), array("type" => "condition")) == "1", "weechat.string_eval_expression('0xA3 > 2', {}, {}, {'type': 'condition'}) == '1'", "87");
    check(weechat_string_eval_expression("\${buffer.full_name}", array(), array(), array()) == "core.weechat", "weechat.string_eval_expression('\${buffer.full_name}', {}, {}, {}) == 'core.weechat'", "88");
}

function test_lists()
{
    weechat_print("", "  > test_lists");
    $ptr_list = weechat_list_new();
    check($ptr_list != "", "ptr_list != ''", "94");
    check(weechat_list_size($ptr_list) == 0, "weechat.list_size(ptr_list) == 0", "95");
    $item_def = weechat_list_add($ptr_list, "def", WEECHAT_LIST_POS_SORT, "");
    check(weechat_list_size($ptr_list) == 1, "weechat.list_size(ptr_list) == 1", "97");
    $item_abc = weechat_list_add($ptr_list, "abc", WEECHAT_LIST_POS_SORT, "");
    check(weechat_list_size($ptr_list) == 2, "weechat.list_size(ptr_list) == 2", "99");
    check(weechat_list_search($ptr_list, "abc") == $item_abc, "weechat.list_search(ptr_list, 'abc') == item_abc", "100");
    check(weechat_list_search($ptr_list, "def") == $item_def, "weechat.list_search(ptr_list, 'def') == item_def", "101");
    check(weechat_list_search($ptr_list, "ghi") == "", "weechat.list_search(ptr_list, 'ghi') == ''", "102");
    check(weechat_list_search_pos($ptr_list, "abc") == 0, "weechat.list_search_pos(ptr_list, 'abc') == 0", "103");
    check(weechat_list_search_pos($ptr_list, "def") == 1, "weechat.list_search_pos(ptr_list, 'def') == 1", "104");
    check(weechat_list_search_pos($ptr_list, "ghi") == (- 1), "weechat.list_search_pos(ptr_list, 'ghi') == (- 1)", "105");
    check(weechat_list_casesearch($ptr_list, "abc") == $item_abc, "weechat.list_casesearch(ptr_list, 'abc') == item_abc", "106");
    check(weechat_list_casesearch($ptr_list, "def") == $item_def, "weechat.list_casesearch(ptr_list, 'def') == item_def", "107");
    check(weechat_list_casesearch($ptr_list, "ghi") == "", "weechat.list_casesearch(ptr_list, 'ghi') == ''", "108");
    check(weechat_list_casesearch($ptr_list, "ABC") == $item_abc, "weechat.list_casesearch(ptr_list, 'ABC') == item_abc", "109");
    check(weechat_list_casesearch($ptr_list, "DEF") == $item_def, "weechat.list_casesearch(ptr_list, 'DEF') == item_def", "110");
    check(weechat_list_casesearch($ptr_list, "GHI") == "", "weechat.list_casesearch(ptr_list, 'GHI') == ''", "111");
    check(weechat_list_casesearch_pos($ptr_list, "abc") == 0, "weechat.list_casesearch_pos(ptr_list, 'abc') == 0", "112");
    check(weechat_list_casesearch_pos($ptr_list, "def") == 1, "weechat.list_casesearch_pos(ptr_list, 'def') == 1", "113");
    check(weechat_list_casesearch_pos($ptr_list, "ghi") == (- 1), "weechat.list_casesearch_pos(ptr_list, 'ghi') == (- 1)", "114");
    check(weechat_list_casesearch_pos($ptr_list, "ABC") == 0, "weechat.list_casesearch_pos(ptr_list, 'ABC') == 0", "115");
    check(weechat_list_casesearch_pos($ptr_list, "DEF") == 1, "weechat.list_casesearch_pos(ptr_list, 'DEF') == 1", "116");
    check(weechat_list_casesearch_pos($ptr_list, "GHI") == (- 1), "weechat.list_casesearch_pos(ptr_list, 'GHI') == (- 1)", "117");
    check(weechat_list_get($ptr_list, 0) == $item_abc, "weechat.list_get(ptr_list, 0) == item_abc", "118");
    check(weechat_list_get($ptr_list, 1) == $item_def, "weechat.list_get(ptr_list, 1) == item_def", "119");
    check(weechat_list_get($ptr_list, 2) == "", "weechat.list_get(ptr_list, 2) == ''", "120");
    weechat_list_set($item_def, "def2");
    check(weechat_list_string($item_def) == "def2", "weechat.list_string(item_def) == 'def2'", "122");
    check(weechat_list_next($item_abc) == $item_def, "weechat.list_next(item_abc) == item_def", "123");
    check(weechat_list_next($item_def) == "", "weechat.list_next(item_def) == ''", "124");
    check(weechat_list_prev($item_abc) == "", "weechat.list_prev(item_abc) == ''", "125");
    check(weechat_list_prev($item_def) == $item_abc, "weechat.list_prev(item_def) == item_abc", "126");
    weechat_list_remove($ptr_list, $item_abc);
    check(weechat_list_size($ptr_list) == 1, "weechat.list_size(ptr_list) == 1", "128");
    check(weechat_list_get($ptr_list, 0) == $item_def, "weechat.list_get(ptr_list, 0) == item_def", "129");
    check(weechat_list_get($ptr_list, 1) == "", "weechat.list_get(ptr_list, 1) == ''", "130");
    weechat_list_remove_all($ptr_list);
    check(weechat_list_size($ptr_list) == 0, "weechat.list_size(ptr_list) == 0", "132");
    weechat_list_free($ptr_list);
}

function test_key()
{
    weechat_print("", "  > test_key");
    check(weechat_key_bind("mouse", array("@chat(plugin.test):button1" => "hsignal:test_mouse", "@chat(plugin.test):wheelup" => "/mycommand up", "@chat(plugin.test):wheeldown" => "/mycommand down", "__quiet" => "")) == 3, "weechat.key_bind('mouse', {'@chat(plugin.test):button1': 'hsignal:test_mouse', '@chat(plugin.test):wheelup': '/mycommand up', '@chat(plugin.test):wheeldown': '/mycommand down', '__quiet': ''}) == 3", "138");
    check(weechat_key_unbind("mouse", "quiet:area:chat(plugin.test)") == 3, "weechat.key_unbind('mouse', 'quiet:area:chat(plugin.test)') == 3", "148");
}

function test_display()
{
    weechat_print("", "  > test_display");
    check(weechat_prefix("action") != "", "weechat.prefix('action') != ''", "153");
    check(weechat_prefix("error") != "", "weechat.prefix('error') != ''", "154");
    check(weechat_prefix("join") != "", "weechat.prefix('join') != ''", "155");
    check(weechat_prefix("network") != "", "weechat.prefix('network') != ''", "156");
    check(weechat_prefix("quit") != "", "weechat.prefix('quit') != ''", "157");
    check(weechat_prefix("unknown") == "", "weechat.prefix('unknown') == ''", "158");
    check(weechat_color("green") != "", "weechat.color('green') != ''", "159");
    check(weechat_color("unknown") == "", "weechat.color('unknown') == ''", "160");
}

function completion_cb($data, $completion_item, $buf, $completion)
{
    check($data == "completion_data", "data == 'completion_data'", "165");
    check($completion_item == "testapi.php", "completion_item == 'SCRIPT_NAME'", "166");
    check(weechat_completion_get_string($completion, "args") == "w", "weechat.completion_get_string(completion, 'args') == 'w'", "167");
    weechat_completion_list_add($completion, "word_completed", 0, WEECHAT_LIST_POS_END);
    return WEECHAT_RC_OK;
}

function command_cb($data, $buf, $args)
{
    check($data == "command_data", "data == 'command_data'", "175");
    check($args == "word_completed", "args == 'word_completed'", "176");
    return WEECHAT_RC_OK;
}

function command_run_cb($data, $buf, $command)
{
    check($data == "command_run_data", "data == 'command_run_data'", "182");
    check($command == "/cmd" . "testapi.php" . " word_completed", "command == '/cmd' + 'SCRIPT_NAME' + ' word_completed'", "183");
    return WEECHAT_RC_OK;
}

function test_hooks()
{
    weechat_print("", "  > test_hooks");
    $hook_cmplt = weechat_hook_completion("testapi.php", "description", "completion_cb", "completion_data");
    $hook_cmd = weechat_hook_command("cmd" . "testapi.php", "description", "arguments", "description arguments", "%(" . "testapi.php" . ")", "command_cb", "command_data");
    weechat_command("", "/input insert /cmd" . "testapi.php" . " w");
    weechat_command("", "/input complete_next");
    $hook_cmd_run = weechat_hook_command_run("/cmd" . "testapi.php" . "*", "command_run_cb", "command_run_data");
    weechat_command("", "/input return");
    weechat_unhook($hook_cmd_run);
    weechat_unhook($hook_cmd);
    weechat_unhook($hook_cmplt);
}

function test_command()
{
    weechat_print("", "  > test_command");
    check(weechat_command("", "/mute") == 0, "weechat.command('', '/mute') == 0", "209");
    check(weechat_command_options("", "/mute", array("commands" => "*,!print")) == 0, "weechat.command_options('', '/mute', {'commands': '*,!print'}) == 0", "210");
    check(weechat_command_options("", "/mute", array("commands" => "*,!mute")) == (- 1), "weechat.command_options('', '/mute', {'commands': '*,!mute'}) == (- 1)", "211");
}

function infolist_cb($data, $infolist_name, $pointer, $arguments)
{
    $infolist = weechat_infolist_new();
    check($infolist != "", "infolist != ''", "217");
    $item = weechat_infolist_new_item($infolist);
    check($item != "", "item != ''", "219");
    check(weechat_infolist_new_var_integer($item, "integer", 123) != "", "weechat.infolist_new_var_integer(item, 'integer', 123) != ''", "220");
    check(weechat_infolist_new_var_string($item, "string", "test string") != "", "weechat.infolist_new_var_string(item, 'string', 'test string') != ''", "221");
    check(weechat_infolist_new_var_pointer($item, "pointer", "0xabcdef") != "", "weechat.infolist_new_var_pointer(item, 'pointer', '0xabcdef') != ''", "222");
    check(weechat_infolist_new_var_time($item, "time", 1231231230) != "", "weechat.infolist_new_var_time(item, 'time', 1231231230) != ''", "223");
    return $infolist;
}

function test_infolist()
{
    weechat_print("", "  > test_infolist");
    $hook_infolist = weechat_hook_infolist("infolist_test_script", "description", "", "", "infolist_cb", "");
    check(weechat_infolist_get("infolist_does_not_exist", "", "") == "", "weechat.infolist_get('infolist_does_not_exist', '', '') == ''", "232");
    $ptr_infolist = weechat_infolist_get("infolist_test_script", "", "");
    check($ptr_infolist != "", "ptr_infolist != ''", "234");
    check(weechat_infolist_next($ptr_infolist) == 1, "weechat.infolist_next(ptr_infolist) == 1", "235");
    check(weechat_infolist_integer($ptr_infolist, "integer") == 123, "weechat.infolist_integer(ptr_infolist, 'integer') == 123", "236");
    check(weechat_infolist_string($ptr_infolist, "string") == "test string", "weechat.infolist_string(ptr_infolist, 'string') == 'test string'", "237");
    check(weechat_infolist_pointer($ptr_infolist, "pointer") == "0xabcdef", "weechat.infolist_pointer(ptr_infolist, 'pointer') == '0xabcdef'", "238");
    check(weechat_infolist_time($ptr_infolist, "time") == 1231231230, "weechat.infolist_time(ptr_infolist, 'time') == 1231231230", "239");
    check(weechat_infolist_fields($ptr_infolist) == "i:integer,s:string,p:pointer,t:time", "weechat.infolist_fields(ptr_infolist) == 'i:integer,s:string,p:pointer,t:time'", "240");
    check(weechat_infolist_next($ptr_infolist) == 0, "weechat.infolist_next(ptr_infolist) == 0", "241");
    weechat_infolist_free($ptr_infolist);
    weechat_unhook($hook_infolist);
}

function cmd_test_cb($data, $buf, $args)
{
    weechat_print("", ">>>");
    weechat_print("", ">>> ------------------------------");
    weechat_print("", ">>> Testing " . "php" . " API");
    weechat_print("", "  > TESTS: " . "107");
    test_plugins();
    test_strings();
    test_lists();
    test_key();
    test_display();
    test_hooks();
    test_command();
    test_infolist();
    weechat_print("", "  > TESTS END");
    return WEECHAT_RC_OK;
}

function weechat_init()
{
    weechat_register("testapi.php", "Sebastien Helleu", "1.0", "GPL3", "Php scripting API test", "", "");
    weechat_hook_command("testapi.php", "", "", "", "", "cmd_test_cb", "");
}

weechat_init();
```

So the line 16 is:

```php
        weechat_print("", "      TEST OK: " . $condition);
```

**Comment by flashcode** [comment]
For your information, I switched from PHP 7.4 to PHP 8.0 in tests executed in CI, and it's now working (I have no idea why).

But I think the error with PHP 7.4 is actually a bug (even if I can not reproduce it manually).

**Comment by adsr** [comment]
>357 commits now, did you rebase by mistake on another branch, or…?

Sorry yes I forgot this PR was `adsr:php8 -> weechat:php8` and I rebased on master. Apologies to anyone that got notified.

> You mentioned a script ~/php-src/build/gen_stub.php in a comment, where can I find this script?

Yes this script lives in the PHP repo here: https://github.com/php/php-src/blob/d9c8e5a42e2f593319ce7b682d43f1f6eb42512e/build/gen_stub.php

> For your information, I switched from PHP 7.4 to PHP 8.0 in tests executed in CI, and it's now working (I have no idea why).
> But I think the error with PHP 7.4 is actually a bug (even if I can not reproduce it manually).

Feel free to assign to me if you file an issue for the cmake/7.4 bugs.

**Pull request closed without merging**
