### PR TITLE
Haiku: link libnetwork, not libpthread.

### PR DESCRIPTION
**Pull request by korli**

### CODE REVIEW

**Comment by flashcode** [comment]
Hi,
Could you please tell me more about the changes? Is `libnetwork` an equivalent of `libpthread`? (the names seem very different, so I'm curious to know what is `libnetwork` on Haiku).
Do you have any pointer on this `libnetwork` lib?

**Comment by korli** [comment]
> Could you please tell me more about the changes? Is `libnetwork` an equivalent of `libpthread`? (the names seem very different, so I'm curious to know what is `libnetwork` on Haiku).
> Do you have any pointer on this `libnetwork` lib?

libnetwork on Haiku is like libsocket on SunOS. For instance connect() and others functions are located in https://github.com/haiku/haiku/blob/master/src/system/libnetwork/socket.cpp#L170

**Comment by flashcode** [comment]
So why replacing `libpthread` and not just adding `libnetwork` on Haiku? libpthread is for threads, not network.

**Comment by korli** [comment]
> So why replacing `libpthread` and not just adding `libnetwork` on Haiku? libpthread is for threads, not network.

libpthread doesn't exist on Haiku, this is by default included in libroot (aka libc).

**Pull request merged**
