### PR TITLE
core: log to stdout, if headless

### PR DESCRIPTION
**Pull request by tomfitzhenry**
Fixes https://github.com/weechat/weechat/issues/1475 .

### CODE REVIEW

**Comment by tomfitzhenry** [comment]
Here's what `weechat-headless` now looks like:

```
$ weechat-headless 
[2020-04-13 00:54:24] WeeChat 2.9-dev (compiled on Jan  1 1970 00:00:01)
[2020-04-13 00:54:24] Reading configuration file sec.conf
[2020-04-13 00:54:24] Reading configuration file weechat.conf
WeeChat is running in headless mode (Ctrl-C to quit).
[2020-04-13 00:54:24] Reading configuration file plugins.conf
[2020-04-13 00:54:24] Reading configuration file charset.conf
[2020-04-13 00:54:24] Reading configuration file logger.conf
[2020-04-13 00:54:24] Reading configuration file exec.conf
[2020-04-13 00:54:24] Reading configuration file trigger.conf
[2020-04-13 00:54:24] Reading configuration file spell.conf
[2020-04-13 00:54:24] Reading configuration file alias.conf
[2020-04-13 00:54:24] Reading configuration file buflist.conf
[2020-04-13 00:54:24] Reading configuration file fifo.conf
[2020-04-13 00:54:24] Reading configuration file xfer.conf
[2020-04-13 00:54:24] Reading configuration file irc.conf
[2020-04-13 00:54:24] Reading configuration file relay.conf
[2020-04-13 00:54:24] Reading configuration file guile.conf
[2020-04-13 00:54:24] Reading configuration file lua.conf
[2020-04-13 00:54:24] Reading configuration file perl.conf
[2020-04-13 00:54:24] Reading configuration file python.conf
[2020-04-13 00:54:24] Reading configuration file ruby.conf
[2020-04-13 00:54:24] Reading configuration file tcl.conf
[2020-04-13 00:54:24] Reading configuration file script.conf
[2020-04-13 00:54:24] Reading configuration file fset.conf
```

**Comment by tomfitzhenry** [comment]
I've just realised a problem with PR: ``weechat-headless --daemon`` does not log, since it now doesn't log to `~/.weechat/weechat.log` and its `stdout` is ignored. I think it should continue to log to `~/.weechat/weechat.log` in this case. I'll update the PR accordingly.

**Comment by tomfitzhenry** [comment]
> I've just realised a problem with PR: weechat-headless --daemon does not log

This is now working:

| Command | Logs to |
|-|-|
| `weechat` | `~/.weechat/weechat.log` |
| `weechat-headless` | stdout |
| `weechat-headless --daemon` | `~/.weechat/weechat.log` |

**Comment by flashcode** [comment]
Nice idea, thanks for the PR.

I wonder though if everybody is OK to have log to stdout with `weechat-headless`, or if it should be optional (for example with a command line argument)?

**Comment by weechatter** [comment]
optional please...

**Comment by flashcode** [comment]
Thanks, merged, and I added a new command line option in weechat-headless binary: `--stdout`.
So the default behavior is unchanged: write log messages in log file.

**Pull request closed without merging**
