### PR TITLE
Respect environment variable WEECHAT_HOME

### PR DESCRIPTION
**Pull request by hashken**
If environment variable WEECHAT_HOME is set to a non-empty value, this
is taken as the path for Weechat home directory.

"--dir" command-line switch has higher precedence over this
environment variable.

### CODE REVIEW

**Comment by hashken** [comment]
This is especially useful for people who want to keep their home directory in accordance to XDG conventions.

**Comment by hashken** [comment]
Will this be merged? Do you need anymore details?

**Comment by flashcode** [comment]
I'll test that very soon and come back to you if ever I have problems.
According to what I see, this is going to be merged (no problem for me).

**Comment by viviskas** [comment]
> If environment variable WEECHAT_HOME is set to a non-empty value, this
> is taken as the path for Weechat home directory.
> 
> "--dir" command-line switch has higher precedence over this
> environment variable.
>

**Pull request merged**
