### PR TITLE
relay: UNIX socket support (implement #733)

### PR DESCRIPTION
**Pull request by ryan-farley**
This adds support for relay servers listening on UNIX domain sockets.
They can be created using the /relay addpath command and specifying the
un protocol option. 'path' is now used instead of 'port' in messages,
which contains either a string representation of the port or the path to
a socket; port is negative when a UNIX socket is used. Path based relays
are stored in their own config section, with existing callbacks reused
as much as possible. Documentation has been updated as well.

### CODE REVIEW

**Comment by ryan-farley** [comment]
Thank you for the review. I've implemented all the requested changes, which do make it a bit simpler (with no new commands and a more sensible protocol option) and actually translatable (the lack of which was just stupid on my part).

**Comment by flashcode** [comment]
I agree with @sim642, I'll rename "un" to "unix" and I'll do some other minor changes (mostly style).
The merge is in progress.

**Comment by flashcode** [comment]
I'll rename to `unix_socket`, since `unix` seems to be a defined integer constant (I have no idea where it is defined).

**Comment by ryan-farley** [comment]
Thank you for even considering this (let alone working to merge it). Regarding `un`, the constant `unix` is why I'd avoided it in the code, but `unix_socket` is more readable, yes.

**Pull request closed without merging**
