### PR TITLE
Fix building on alpine linux

### LINKED ISSUE #1402: Additional library libintl needed when building on Alpine with ENABLE_NLS=ON
## Bug summary

When building on Alpine Linux, it is necessary to link against libintl.so for the gettext functions. Since Alpine uses musl libc rather than GNU libc, the gettext functions are *not* present in the C standard library.

## Steps to reproduce

```sh
apk update && \
apk add --no-cache ncurses zlib libgcrypt curl gnutls libintl && \
apk add --no-cache alpine-sdk cmake libgcrypt-dev zlib-dev curl-dev ncurses-dev gnutls-dev gettext-dev && \
git clone https://github.com/weechat/weechat.git && \
cd weechat && \
mkdir build && cd build && \
cmake .. -DENABLE_RUBY=0 -DENABLE_LUA=0 -DENABLE_PHP=0 -DENABLE_JAVASCRIPT=0 -DENABLE_DOC=0 -DENABLE_TESTS=0 -DENABLE_GUILE=0 -DENABLE_TCL=0 -DENABLE_PYTHON=0 -DENABLE_RELAY=0 -DENABLE_ENCHANT=0 -DENABLE_MAN=0 -DENABLE_SPELL=0 -DENABLE_PERL=0 && \
make
```

## Current behavior

```
[ 92%] Linking C executable weechat
cd /weechat/build/src/gui/curses/normal && /usr/bin/cmake -E cmake_link_script CMakeFiles/weechat.dir/link.txt --verbose=1
/usr/bin/cc  -fsigned-char -Wall -Wextra -Werror-implicit-function-declaration  -L/usr/lib -L/usr/lib -rdynamic CMakeFiles/weechat.dir/main.c.o  -o weechat ../../libweechat_gui_common.a ../../../plugins/libweechat_plugins.a ../../../core/libweechat_core.a ../../libweechat_gui_common.a libweechat_gui_curses_normal.a -lgcrypt -lgpg-error -lgnutls -ldl -lpthread -liconv -lm -lcurl -lncursesw ../../libweechat_gui_common.a ../../../plugins/libweechat_plugins.a ../../../core/libweechat_core.a ../../libweechat_gui_common.a       /usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: ../../../core/libweechat_core.a(weechat.c.o): in function `weechat_display_copyright':
weechat.c:(.text+0x57): undefined reference to `libintl_gettext'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: ../../../core/libweechat_core.a(weechat.c.o): in function `weechat_display_usage':     weechat.c:(.text+0xf6): undefined reference to `libintl_gettext'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: weechat.c:(.text+0x13a): undefined reference to `libintl_gettext'
```

## Expected behavior

```
[100%] Linking C executable weechat
```

## Suggested solutions

Add ```find_package(Intl)``` to CMakeList.txt and add Intl_LIBARARIES to the list of libs to link against if found.

Something similar to this diff:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6f5820225..78eaed395 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -180,6 +180,12 @@ if(ENABLE_NLS)
   find_package(Gettext)
   if(GETTEXT_FOUND)
     add_definitions(-DENABLE_NLS)
+    find_package(Intl)
+    if(Intl_FOUND)
+      list(APPEND EXTRA_LIBS "${Intl_LIBRARY}") 
+    else()
+      message(SEND_ERROR "Intl not found")
+    endif()
   else()
     message(SEND_ERROR "Gettext not found")
   endif()
```

## Additional information

From cmake's FindIntl.cmake:

```
# Find the Gettext libintl headers and libraries.
#
# This module reports information about the Gettext libintl
# installation in several variables.  General variables::
#
#   Intl_FOUND - true if the libintl headers and libraries were found
#   Intl_INCLUDE_DIRS - the directory containing the libintl headers
#   Intl_LIBRARIES - libintl libraries to be linked
#
# The following cache variables may also be set::
#
#   Intl_INCLUDE_DIR - the directory containing the libintl headers
#   Intl_LIBRARY - the libintl library (if any)
#
# .. note::
#   On some platforms, such as Linux with GNU libc, the gettext
#   functions are present in the C standard library and libintl
#   is not required.  ``Intl_LIBRARIES`` will be empty in this
#   case.
```

Based on this, adding Intl_LIBRARIES to EXTRA_LIBS should always be safe, since the value will only be set if necessary and will remain empty on Debian/Ubuntu/most everything else.

---

- WeeChat version: HEAD
- OS, distribution and version: Alpine latest

### PR DESCRIPTION
**Pull request by Robo210**
Explicitly add libintl to the list of libraries to link against. This fixes linking on systems not using GNU libc.

Tested with Ubuntu (gettext is part of its libc) and Alpine (requires explicitly linking against libintl.lib). Fixes #1402

### CODE REVIEW

**Comment by Robo210** [comment]
I see this is tagged as "waiting info" - "Waiting for info from author of issue". Is there anything specific you need to know from me?

**Comment by flashcode** [comment]
@Robo210: yes I started a review with a comment on your code changed, do you see it?
I suggested to search for Intl but make it optional, as it can break on some distros (but compilation is fine without it).

**Comment by Robo210** [comment]
Sorry, but I don't see any comments on the code. I'll make the search optional though and send out an update over the weekend.

**Comment by flashcode** [comment]
I can do it, not a problem, I'll merge and make intl optional.

**Pull request closed without merging**
